[15] Log opened at 2024-11-18 07:08:53.736165
[15] [Config] INFO: Control socket set up succesfully: '@xdebug-ctrl.15'
[15] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[15] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[15] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[15] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[47] Log opened at 2024-11-18 07:08:55.604633
[47] [Config] INFO: Control socket set up succesfully: '@xdebug-ctrl.47'
[47] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[47] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[47] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[47] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[47] Log closed at 2024-11-18 07:08:55.609008

[285] Log opened at 2024-11-18 07:09:10.320198
[285] [Config] INFO: Control socket set up succesfully: '@xdebug-ctrl.285'
[285] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[285] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[285] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[285] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[285] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[285] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[285] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[285] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[285] Log closed at 2024-11-18 07:09:10.454144

[290] Log opened at 2024-11-18 07:09:10.625408
[290] [Config] INFO: Control socket set up succesfully: '@xdebug-ctrl.290'
[290] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[290] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[290] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[290] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[290] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[290] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[290] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[290] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[290] Log closed at 2024-11-18 07:09:10.747324

[295] Log opened at 2024-11-18 07:09:10.951928
[295] [Config] INFO: Control socket set up succesfully: '@xdebug-ctrl.295'
[295] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[295] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[295] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[295] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[295] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[295] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[295] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[295] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[295] Log closed at 2024-11-18 07:09:11.069984

[15] Log closed at 2024-11-18 07:09:11.097175

[8] Log opened at 2024-11-18 07:12:08.121789
[8] [Config] INFO: Control socket set up succesfully: '@xdebug-ctrl.8'
[8] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[8] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[8] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[8] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[8] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[8] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[8] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[8] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[8] Log closed at 2024-11-18 07:12:08.371159

[7] Log opened at 2024-11-18 07:12:15.272240
[7] [Config] INFO: Control socket set up succesfully: '@xdebug-ctrl.7'
[7] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[7] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[7] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[7] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[7] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[7] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[7] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[7] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[7] Log closed at 2024-11-18 07:12:15.451069

